title: Sameiet Kirkeveien 90
description: En enkel hjemmeside for Sameiet Kirkeveien 90 som skal samle info som hyppig blir etterspurt
theme: just-the-docs
logo: assets/images/logo.png

url: https://www.kirkeveien90.no

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
  #Kirkeveien: https://kirkeveien90.no

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Rediger denne siden på GitHub."
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_repository: https://github.com/sameiet-kirkeveien-90/sameiet-kirkeveien-90.github.io
gh_edit_view_mode: "edit"

plugins: 
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

nav_external_links:
  - title: Facebookgruppe for Kirkeveien 90
    url: https://www.facebook.com/groups/kirkeveien90/
    opens_in_new_tab: true 
  - title: Husordensregler
    url: https://www.dropbox.com/scl/fi/woqsyy767g218yk8906b5/20250507-Husordensregler.pdf?rlkey=h0n8ak7yevref8wz6fghpsz6y&st=wzuhd3b6&dl=0
    opens_in_new_tab: true 
  - title: Vedtekter
    url: https://www.dropbox.com/scl/fi/so8pw6avq44tmhu4pg8vi/VEDTEKTER-28.-april-2014.doc?rlkey=4zvgmblv4uue6kxyglsdwkkl6&st=31xyo3vi&dl=0
    opens_in_new_tab: true 
  - title: Utsendt til sameiere
    url: https://www.dropbox.com/scl/fo/imy36unu5h3jculdlo7c0/AO0L1bzPSh4ebXPCDyvh4e4?rlkey=kb0po3veh7kjs7c35v9wn7hf0&st=nxakm8qu&dl=0
    opens_in_new_tab: true 

# dette bestemmer farger for infobokser, etc
# ref https://just-the-docs.com/docs/configuration/#callouts
# ref https://just-the-docs.com/docs/ui-components/callouts/
callouts:
  info:
    title: Info
    color: blue
